[package]
name = "dblefr"
version = "0.1.0"
edition = "2024"

[dependencies]
gif = "0.13.3"
image = "0.25.8"
rayon = "1.11.0"
eframe = "0.28.0"
egui = "0.28.0"
egui_plot = "0.28.0"
crossbeam-channel = "0.5.12"
